# Generated by Django 5.0.2 on 2025-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='eula_agreed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
