# Generated by Django 5.0.2 on 2025-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_core', '0002_remove_user_created_at_remove_user_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('search', 'Search'), ('add_contact', 'Add Contact'), ('edit_contact', 'Edit Contact'), ('delete_contact', 'Delete Contact'), ('upload_photo', 'Upload Photo'), ('referral', 'Referral'), ('score_change', 'Score Change'), ('password_change', 'Password Change')], max_length=20),
        ),
    ]
