# Generated by Django 5.0.2 on 2025-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_core', '0003_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('atoll', models.CharField(blank=True, max_length=100)),
                ('island_type', models.CharField(choices=[('inhabited', 'Inhabited Island'), ('uninhabited', 'Uninhabited Island'), ('resort', 'Resort Island'), ('airport', 'Airport Island'), ('capital', 'Capital Island')], default='inhabited', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Island',
                'verbose_name_plural': 'Islands',
                'ordering': ['name'],
            },
        ),
    ]
