# Generated by Django 5.0.2 on 2025-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='is_manually_updated',
            field=models.BooleanField(default=False, help_text='Whether this family has been manually updated by a user'),
        ),
    ]
