# Generated by Django 5.0.2 on 2025-08-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_family', '0003_alter_familygroup_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familygroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='parent_family',
            field=models.ForeignKey(blank=True, help_text='Parent family group if this is a sub-family', null=True, on_delete=django.db.models.deletion.CASCADE, to='dirReactFinal_family.familygroup'),
        ),
    ]
