# Generated by Django 5.0.2 on 2025-09-10 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_directory', '0010_add_status_choices_and_is_unlisted'),
        ('dirReactFinal_family', '0004_alter_familygroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrelationship',
            name='confidence_level',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=100, help_text='Confidence level in the accuracy of this relationship (0-100%)'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this relationship ended (e.g., divorce date, death date)', null=True),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='is_biological',
            field=models.BooleanField(default=True, help_text='Whether this is a biological relationship'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='is_legal',
            field=models.BooleanField(default=False, help_text='Whether this relationship has legal recognition'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended'), ('suspended', 'Suspended')], default='active', help_text='Current status of the relationship', max_length=20),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this relationship began (e.g., marriage date, adoption date)', null=True),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('aunt_uncle', 'Aunt/Uncle'), ('niece_nephew', 'Niece/Nephew'), ('cousin', 'Cousin'), ('step_parent', 'Step-Parent'), ('step_child', 'Step-Child'), ('step_sibling', 'Step-Sibling'), ('half_sibling', 'Half-Sibling'), ('father_in_law', 'Father-in-Law'), ('mother_in_law', 'Mother-in-Law'), ('son_in_law', 'Son-in-Law'), ('daughter_in_law', 'Daughter-in-Law'), ('brother_in_law', 'Brother-in-Law'), ('sister_in_law', 'Sister-in-Law'), ('adopted_parent', 'Adopted Parent'), ('adopted_child', 'Adopted Child'), ('legal_guardian', 'Legal Guardian'), ('ward', 'Ward'), ('foster_parent', 'Foster Parent'), ('foster_child', 'Foster Child'), ('godparent', 'Godparent'), ('godchild', 'Godchild'), ('sponsor', 'Sponsor'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='FamilyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('certificate', 'Certificate'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='dirReactFinal_family.familygroup')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='dirReactFinal_directory.phonebookentry')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='dirReactFinal_family.familyrelationship')),
            ],
            options={
                'verbose_name': 'Family Media',
                'verbose_name_plural': 'Family Media',
                'db_table': 'family_media',
            },
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('marriage', 'Marriage'), ('divorce', 'Divorce'), ('adoption', 'Adoption'), ('graduation', 'Graduation'), ('migration', 'Migration'), ('religious_ceremony', 'Religious Ceremony'), ('anniversary', 'Anniversary'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='dirReactFinal_directory.phonebookentry')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='dirReactFinal_directory.phonebookentry')),
                ('media_attachments', models.ManyToManyField(blank=True, related_name='events', to='dirReactFinal_family.familymedia')),
            ],
            options={
                'verbose_name': 'Family Event',
                'verbose_name_plural': 'Family Events',
                'db_table': 'family_events',
                'ordering': ['-event_date'],
            },
        ),
    ]
