# Generated by Django 5.0.2 on 2025-09-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_family', '0005_add_phase4_relationship_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyevent',
            name='verification_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='family_media/'),
        ),
        migrations.AddField(
            model_name='familymedia',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='familymedia',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
