# Generated by Django 5.0.2 on 2025-09-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_family', '0006_add_missing_phase4_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyevent',
            name='event_type',
            field=models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('marriage', 'Marriage'), ('divorce', 'Divorce'), ('adoption', 'Adoption'), ('graduation', 'Graduation'), ('migration', 'Migration'), ('religious_ceremony', 'Religious Ceremony'), ('anniversary', 'Anniversary'), ('employment', 'Employment'), ('retirement', 'Retirement'), ('illness', 'Illness'), ('recovery', 'Recovery'), ('other', 'Other')], max_length=30),
        ),
    ]
