# Generated by Django 5.0.2 on 2025-09-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_family', '0007_add_missing_event_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrelationship',
            name='confidence_level',
            field=models.IntegerField(default=100, help_text='Confidence level in the accuracy of this relationship (0-100%)'),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended'), ('suspended', 'Suspended'), ('divorced', 'Divorced')], default='active', help_text='Current status of the relationship', max_length=20),
        ),
    ]
