# Generated by Django 5.0.2 on 2025-09-10 04:22

import dirReactFinal_family.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_family', '0008_fix_model_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=dirReactFinal_family.models.family_media_upload_path),
        ),
    ]
