# Generated by Django 5.0.2 on 2025-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_directory', '0007_resolve_field_mismatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookentry',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
