# Generated by Django 5.0.2 on 2025-08-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_core', '0006_atoll_party'),
        ('dirReactFinal_directory', '0008_alter_phonebookentry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookentry',
            name='address',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='atoll',
            field=models.ForeignKey(blank=True, db_column='atoll_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dirReactFinal_core.atoll'),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='gender_choice', db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='island',
            field=models.ForeignKey(blank=True, db_column='island_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dirReactFinal_core.island'),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='nid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='party',
            field=models.ForeignKey(blank=True, db_column='party_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dirReactFinal_core.party'),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='profession',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='remark',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['address'], name='t1_address_ea6b32_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['profession'], name='t1_profess_d132f2_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['remark'], name='t1_remark_a5b284_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['atoll'], name='t1_atoll_f_39e480_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['island'], name='t1_island__78015b_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['party'], name='t1_party_f_cdbe60_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['gender'], name='t1_gender__d9c635_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['name', 'address'], name='t1_name_eb8264_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['address', 'island'], name='t1_address_9f8b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebookentry',
            index=models.Index(fields=['name', 'party'], name='t1_name_56871a_idx'),
        ),
    ]
