# Generated by Django 5.0.2 on 2025-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirReactFinal_directory', '0009_add_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebookentry',
            name='is_unlisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='phonebookentry',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('deceased', 'Deceased'), ('unlisted', 'Unlisted'), ('inactive', 'Inactive'), ('outdated', 'Outdated')], db_index=True, max_length=20, null=True),
        ),
    ]
